(define (full-adder a b c) (comb (or-gate (and-gate a b) (and-gate a c) (and-gate b c)) (xor-gate a b c)))

(define (CRA A B C)
	(if (= 0 (width A)) C
	(let0 lwadd (full-adder (low A) (low B) (high C))
	(CRA (rmlow A) (rmlow B) (comb lwadd (rmhigh C)))
)))


(define (CSA A B C0)
	(if (= 1 (width A)) (full-adder A B C0)
	(let0 lwadd (CSA (lwhalf-cl A) (lwhalf-cl B) C0)
		(comb (MIF (high lwadd)  
				(CSA (hihalf A) (hihalf B) bit1)
				(CSA (hihalf A) (hihalf B) bit0))
			(rmhigh lwadd))
)))

(define (FA x y c)
	(unite (F G P)
		(xor-gate x y c) 
		(and-gate x y)
		(or-gate x y)
))
(define (CLA G1 P1 G0 P0 C-1)
	(unite (C G P)
		(or-gate G0 (and-gate P0 C-1))
		(or-gate G1 (and-gate P1 G0))
		(and-gate P1 P0)
))
(define (adderD A B C-1)
	(if (= 1 (width A)) (FA A B C-1)
	(let0 C0 (pin 1)
	(split (F1 G1 P1) (adderD (hihalf A) (hihalf B) C0)
	(split (F0 G0 P0) (adderD (lwhalf-cl A) (lwhalf-cl B) C-1)
	(split (C G P) (CLA G1 P1 G0 P0 C-1)
	(link-wire C0 C)
	(unite (F G P) (comb F1 F0) G P)
))))))
(define (CLA A B C-1)
	(if (= 1 (width A)) (unite (F G P) (xor-gate A B C-1) (and-gate A B) (or-gate A B))
	(let0 C0 (pin 1 0)
	(split (F1 G1 P1) (CLA (hihalf A) (hihalf B) C0)
	(split (F0 G0 P0) (CLA (lwhalf-cl A) (lwhalf-cl B) C-1)
	(link-wire C0 (or-gate G0 (and-gate P0 C-1)))
	(unite (F G P) (comb F1 F0) (or-gate G1 (and-gate P1 G0)) (and-gate P1 P0))
)))))
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(define (decoder code e)
	(if (= 0 (width code)) e
	(let0 rhdec (decoder (rmhigh code) e)
	(comb (Cbuffer (high code) rhdec) (Cbuffer (not-gate (high code)) rhdec))
)))

(define (MUX wires sel)
	(if (wire? wires) wires
	(MIF (high sel) (MUX (cdr wires) (rmhigh sel))
					(MUX (car wires) (rmhigh sel)))
))

(define (DEMUX1 wire sel)
	(cons (Cbuffer sel wire) (Cbuffer (not-gate sel) wire)
))
(define (DEMUX wire sel)
	(if (= 0 (width sel)) wire
	(let0 DEM1 (DEMUX1 wire (high sel))
	(cons (DEMUX (car DEM1) (rmhigh sel))
			(DEMUX (cdr DEM1) (rmhigh sel)))
)))